# Generated by Django 3.0.3 on 2024-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
